### ISSUE TITLE
Train code

### ISSUE THREAD

**Issue by SSSKYue** [dvl-tum/center-group#1]
Hello, sorry to bother you.
I'm so interested in your good work, and I want to learn more details.
Could u please release the training code at your convinience?
Best regards!

**Comment by gbraso** [comment]
Hi,

Thanks a lot for your interest in our work. I'm actively working on this and the training code should be released, at the latest, next week.

Thank you for your patience!!

Guillem

**Comment by guillembraso** [comment]
Hi,

Sorry for the delay. The training code has been finally released. Note that you will have to install PyTorch Lightning to use it! 

Thanks for your patience again!!

Guillem
