### ISSUE TITLE
How to set the input size?

### ISSUE THREAD

**Issue by calmisential** [dvl-tum/center-group#4]
Hello, I didn't find the param 'input size' in `higherhrnet_w32_coco_512x512.py` and `higherhrnet_w48_crowdpose_640x640.py`. If I want to train centergroup from the scratch, how could I set the hyper parammeters such as 'input size', 'epoch', 'optimizer', 'lr schedule'?

**Comment by guillembraso** [comment]
Hi, for `higherhrnet_w32_coco_512x512.py`, the input size is set in the `base` config, in [this line](https://github.com/dvl-tum/center-group/blob/87c2d831e63c044684450d72c1c6f3e568175c14/configs/centergroup/base.py#L23). For `higherhrnet_w48_crowdpose_640x640` your comment made me realize that I did not set the input size correctly, so thanks! Now you can find it under `data_cfg`. Lastly, the optimizer params are set [here](https://github.com/dvl-tum/center-group/blob/9e55c06bbc9c59f7eb3d86c847f9a7880c164165/configs/centergroup/base.py#L190) in the base config. For training from scratch, I'd still recommend pretraining HigherHRNet with centers first, though!

**Comment by calmiLovesAI** [comment]
Thank you!

**Comment by chenrxi** [comment]
> Hi, for `higherhrnet_w32_coco_512x512.py`, the input size is set in the `base` config, in [this line](https://github.com/dvl-tum/center-group/blob/87c2d831e63c044684450d72c1c6f3e568175c14/configs/centergroup/base.py#L23). For `higherhrnet_w48_crowdpose_640x640` your comment made me realize that I did not set the input size correctly, so thanks! Now you can find it under `data_cfg`. Lastly, the optimizer params are set [here](https://github.com/dvl-tum/center-group/blob/9e55c06bbc9c59f7eb3d86c847f9a7880c164165/configs/centergroup/base.py#L190) in the base config. For training from scratch, I'd still recommend pretraining HigherHRNet with centers first, though!

how many gpus use in training. @guillembraso
